version: '3.4'

services:
  bazaar-and-more:
    image: AidesOnTheGo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7000:7000
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'index.js']
